config/routes.rb
JoshIntranet::Application.routes.draw do


devise_for :users, :path_names => {
    :sign_in => 'login',
    :sign_out => 'logout',
    :controller => {:invitations => 'devise/invitations'},
    :root_path => 'leaves#index'    
  }
  
  match '/signup' => 'organizations#new', via: :get, as: :signup 
  match '/signup' => 'organizations#create', via: :post, as: :signup


  constraints(OrganizationRoutes) do
    match "/" => 'dashboard#index'
    resources :users
    resources :leaves do
      get :approve, on: :member
      put :approve, on: :member
      get :rejectStatus, on: :member
      put :rejectStatus, on: :member
    end

    resources :leave_details
    resources :leave_types

    match '/addleaves' => 'users#addleaves', :via => :get
    match '/users/:user_id/assignleaves' => 'users#assignleaves', :via => [:get, :post], as: :assignleaves
    match '/users/:user_id/profile' => 'users#profile', :via => [:get, :post], as: :profile
    match '/users/:user_id/reinvite' => 'users#reinvite', :via => :get, as: :reinvite
    match '/leavessummary' => 'users#leavessummary', :via => :get,  as: :leavessummary
    match '/users/:user_id/chengeroles' => 'users#chengeroles', :via => [:get, :post], as: :chengeroles
    match '/users/:user_id/chengemanager' => 'users#chengemanager', :via => [:get, :post], as: :chengemanager
    match '/organization/:organization_id/csv' => 'users#upload_csv', :via => [:get, :put ], as: :upload_csv
    match '/managers' => 'users#managers', :via => :get, as: :managers
    match '/leave_summary_for_roles' => 'users#leave_summary_for_roles', :via => :get 
    match '/users/:user_id/leave_summary_on_roles' => 'users#leave_summary_on_roles', :via => [:get, :post], as: :leave_summary_on_roles
    match 'calenderhelp' => 'home#calenderhelp', :via => :get
  end









  root :to => 'home#index'


end

app/models/user.rb
class User
  include Mongoid::Document
  include Mongoid::Document::Roleable

  include Mongoid::Paperclip 
  has_mongoid_attached_file :leaving_Certificate

  paginates_per 10

  embeds_one :profile
  accepts_nested_attributes_for :profile
  attr_accessible :profile_attributes

  embeds_many :leave_details
  accepts_nested_attributes_for :leave_details
  attr_accessible :leave_details_attributes
  ROLES = ['Admin', 'HR', 'Manager', 'Employee']
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :invitable, :database_authenticatable, :registerable,
    :recoverable, :rememberable, :trackable, :validatable


  ## Database authenticatable
  field :email,              :type => String, :default => ""
  field :encrypted_password , :default => ""
  field :join_date, type: Date
  field :employee_id, type: Integer
  field :probation_end_date, type: Date
  field :pay_role, type: Boolean
  field :next_year_of_probation_date, type: Date
  validates :join_date, :employee_id, :roles, :presence => true
  validates :employee_id, :uniqueness => {:scope => :organization_id}
  #validates :email, :presence => true
#  validates_uniqueness_of :email, :scope => :organization_id

#  validates :email, :format => {:with => /^[-a-z0-9_+\.]+\@([-a-z0-9]+\.)+[a-z0-9]{2,4}$/i , :message => "Invalid email address" }
 # validates_attachment :leaving_Certificate, :presence => true, :content_type => { :content_type => ['image/jpg', 'image/png', 'image/jpeg']}

  attr_accessible :email, :password, :password_confirmation, :roles, :organization_id, :join_date, :employee_id, :manager_id, :probation_end_date, :pay_role, :leaving_Certificate
  ## Recoverable
  field :reset_password_token,   :type => String
  field :reset_password_sent_at, :type => Time

	 ## Rememberable
  field :remember_created_at, :type => Time

  ## Trackabler
  field :sign_in_count,      :type => Integer, :default => 0
  field :current_sign_in_at, :type => Time
  field :last_sign_in_at,    :type => Time
  field :current_sign_in_ip 
  field :last_sign_in_ip,    :type => String

  ## Confirmable
  field :confirmation_token,   :type => String
  field :confirmed_at,         :type => Time
  field :confirmation_sent_at, :type => Time
  field :unconfirmed_email,    :type => String # Only if using reconfirmable

  ## Invitable
  field :invitation_token
  field :invitation_sent_at, type: Time
  field :invitation_accepted_at, type: Time
  field :invitation_limit, type: Integer
  field :invited_by_id, type: Integer
  field :invited_by_type
  field :invitation_created_at
  ## Lockable
  # field :failed_attempts, :type => Integer, :default => 0 # Only if lock strategy is :failed_attempts
  # field :unlock_token,    :type => String # Only if unlock strategy is :email or :both
  # field :locked_at,       :type => Time

  ## Token authenticatable
  # field :authentication_token 

  belongs_to :organization
  has_many :leaves, class_name: "Leave", dependent: :destroy

  # using self joyngs to maintain the relationship between employee and manager.
  has_many :employees, class_name: "User", :foreign_key => "manager_id"
  belongs_to :manager, class_name: "User"

  # use the name field directly user field for example @user.name
  delegate :name, :to => :profile
  def send_confirmation_instructions
    super
    self.confirmation_token = nil    # clear's the confirmation_token
    self.confirmed_at = Time.now.utc # confirm's the user
    self.save
  end

  def self.date_of_birth
    date = Date.today+3
    o  = Organization.all
    o.each do |organization|
      admin = organization.users.where(:roles => 'Admin').collect(&:email)
      users = organization.users.in(:roles => ['HR', 'Manager', 'Employee'])
      users.each do |user|
        if user.profile != nil
          if user.profile.dateOfBirth.try(:strftime, "%j").to_i == Date.today.strftime("%j").to_i+3
            UserMailer.date_of_birth(user, admin, date).deliver
          end
        end
      end
    end
  end

  def self.leave_details_every_month
    organization = Organization.all
    organization.each do |o|
      user_admin = User.where(:roles => 'Admin').collect(&:email)
      users  = o.users.in(:roles => ['HR', 'Manager', 'Employee'])
#        another_user = User.in(:roles => ['HR', 'Manager', 'Employee']).collect(&:email)
      users.each do |user|
        user.leave_details.each do |leave|
          if leave.assign_date.year == Time.zone.now.year
            UserMailer.send_leave(user_admin, user.email, leave).deliver
          end
        end
      end
    end
  end

  def self.send_mail_to_admin
    organization = Organization.all
    organization.each do |o|
      admin = o.users.where(:roles => 'Admin').collect(&:email)
      user = o.users.in(:roles => ['HR', 'Manager', 'Employee'])
      UserMailer.send_mail_to_admin(admin, user).deliver
    end
  end

  def self.email_of_probation
    date = Date.today+15
    organization = Organization.all
    organization.each do |o|
      admin = o.users.where(:roles => 'Admin').collect(&:email)
      users = o.users.in(:roles => ['HR', 'Manager', 'Employee'])
      users.each do |user|
        if user.probation_end_date.try(:strftime, "%j").to_i == Date.today.strftime("%j").to_i+15
          UserMailer.email_of_probation(admin, user, date).deliver
        end
      end
    end
  end
end

app/controllers/users_controller.rb
class UsersController  < ApplicationController
  before_filter :authenticate_inviter!, :only => [:new, :create]
#  load_and_authorize_resource 
  skip_authorize_resource :only => :index

  def calenderhelp
    respond_to do |format|
      format.js
    end
  end

  def index
    @users = current_organization.users.ne(email: current_user.email).page(params[:page])
    Kaminari.paginate_array(@users).page(params[:page])
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  def edit
    @user = User.find(params[:id])

    @user.build_profile if @user.profile.nil?
  end

  def update
    @user = User.find(params[:id])
    @user.update_attributes(params[:user_roles])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end

  def assignleaves
    @user = User.find(params[:user_id])
    @leave_types = current_organization.leave_types.all
    if request.get?
      if @user.leave_details.empty?
        @user.leave_details.build(:assign_date => Date.today)
        @assign_leaves = calculate_leaves
      else
        @assign_leaves = @user.leave_details.last.assign_leaves
      end
    elsif request.post?
      @user.leave_details.build if @user.leave_details.empty?
      @user.leave_details.last.assign_date = params[:date]
      @user.leave_details.last.assign_leaves = params[:assign_leaves]
      params[:assign_leaves].keys.each do |lt_id|
        if @user.leave_details.last.available_leaves[lt_id.to_s].nil?
          @user.leave_details.last.available_leaves[lt_id] = params[:assign_leaves][lt_id.to_s]
        else 
#         @user.leave_details.last.available_leaves[lt_id].each do |a_l|
        if @user.leave_details.last.available_leaves[lt_id].to_f > params[:assign_leaves][lt_id].to_f
          @user.leave_details.last.available_leaves[lt_id] = params[:assign_leaves][lt_id.to_s]
        end



        end
      end
      @user.leave_details.last.save
      redirect_to addleaves_path, notice: "leaves has been assign successfully."
    end    
  end

  def chengeroles
    @user = User.find(params[:user_id])
      if request.post?
      respond_to do |format|
        if @user.update_attributes(params[:user])
          format.html { redirect_to users_path, notice: 'Role has been changed !'  }
    end
     end
    end
    end

  def chengemanager
        @user = User.find(params[:user_id])
      if request.post?
      respond_to do |format|
        if @user.update_attributes(params[:user])
          format.html { redirect_to users_path, notice: 'Manager has been changed !'  }
    end
     end
    end
    end

  def profile
    @user = User.find(params[:user_id])
    if request.post?
      respond_to do |format|
        if @user.update_attributes(params[:user])
          format.html { redirect_to profile_path(@user), notice: 'Profile was successfully updated!'  }
        else
          format.html { render action: "edit" }
	  format.json { render json: @user.errors, status: :unprocessable_entity }
        end
      end
    end
  end

  def reinvite
    @user = User.find(params[:user_id])
    @user.invite!(current_user)
  end

  def leavessummary  
    @leave_details = current_user.leave_details.all
    @leave_types = current_organization.leave_types.all
  end

  def upload_csv     
    @organization = Organization.find(params[:organization_id])
    respond_to do |format|
       if request.put?
         if @organization.update_attributes(params[:organization]) 
            invite_users
            format.html{ render "upload"}	    
         else
           format.html {render action: "upload_csv"}
	 end
       else
          format.html {render action: "upload_csv"}
      end
    end
  end

  def invite_users
    headers = {}
    @invited_users = []
    CSV.foreach(current_organization.csv_attachment.path) do |row|
      invite_params = {}
      if headers.length ==0
        # First row is known as headers.
        # Fill the hash with the headers
        # Each header value would be key
        row.each do |k|
          headers[k] = ""
        end
      else
        # Fill the hash with row values for each key
        index = 0
        headers.keys.each do |k|
          invite_params.store(k, row[index])
          index = index + 1

        end
        if invite_params["manager"] != nil
          invite_params["manager"] = User.find_by(:email => invite_params["manager"]).id
        end
        invite_params["organization_id"] = current_organization.id
        user = User.invite!(invite_params, current_user)
        if user.errors.messages == {}
        @leave_types = current_organization.leave_types.all
        assign_leaves =calculate_leaves
        user.leave_details.build if user.leave_details[0].nil?
        user.leave_details[0].assign_date = Date.today
        user.leave_details[0].assign_leaves = assign_leaves
        user.leave_details[0].available_leaves = assign_leaves
        user.leave_details[0].save
        end
        @invited_users.push(user)
      end
    end
  end

  def managers
    organization = Organization.find_by(:name => request.subdomain)
    user_params = request.query_string.split(",", 2)
    if user_params != nil
      email = user_params[0]
      password = user_params[1]
      user = organization.users.find_by(:email => email)
    end
    if user != nil
      if user.valid_password?(password) == true
    users = organization.users.where(:roles => "Manager")
    responseText = nil
    users.each do |u|
      if responseText == nil
        responseText = u.email
      else
        responseText = responseText + "," + u.email
      end
    end
    render :text => responseText, :content_type => "text/plain"
      end
    else
    render :text => "invalid", :content_type => "text/plain"
    end
  end

    def leave_summary_on_roles
      @user = User.find(params[:user_id])
      @leave_details = @user.leave_details.all
      @leave_types = current_organization.leave_types.all
    end  

end


app/helpers/user_helper.rb
module UserHelper
end

app/views/users/_calenderhelp.html.haml
%p
  %ul
    %li Activate the Calendar link to open the Calendar Picker control.
    %li Mouse users can click the Left or Right arrows to navigate by month, or click a date to set focus to a selection; Click the selection that has focus to save the date and close the calendar.
    %li Keyboard users can press the Arrow keys to navigate by date in the same manner as a tabular grid; Press the Home or End keys to move to the beginning or end of a row.
    %li Press Shift+Tab to activate the Previous Month or Next Month buttons, press PageDown or PageUp to move backward or forward in one month intervals, or press Alt+PageDown or Alt+PageUp to move backward or forward in one year intervals instead.
    %li Press Enter on a date to make a selection, or press Escape or Tab to close the popup.
    %li In Advanced Mode, press the Spacebar on a date to open the Comment Editor, or click the Edit button instead.
  

app/views/users/_chengemanager.html.haml
- content_for :javascript do
  = javascript_include_tag 'user'
= simple_form_for  @user, url: chengemanager_path(@user), method: :post,  html: {:class => 'form-horizontal'} do |f|
  = f.error_notification
  = f.input :manager, :collection => current_organization.users.where(:roles => 'Manager'), :label_method => :email, :prompt => "Select manager", :label => 'Manager', :id => 'commanagerid'
  .form-actions
    = f.button :submit, :class => 'btn btn-success'
    = link_to 'Cancel', users_path, :class => 'btn btn-danger'

app/views/users/_frmprofile.html.haml
- content_for :javascript do
  = javascript_include_tag 'user', 'setup_dateOfBirth'
= simple_form_for @user, url: profile_path(@user), method: :post, html: {:class => 'form-horizontal'} do |u|
  = u.error_notification

  = u.simple_fields_for :profile do |p|

    .form-inputs

      = p.input :name
      = p.input :local_address, :as => :text, :required => true, :input_html => {:cols => 20, :rows => 5}
      = p.input :permanent_address, :as => :text, :required => true, :input_html => {:cols => 20, :rows => 5}
      = p.input :phone_number, :label => 'Mobile number'
      = p.input :dateOfBirth, :label => 'Date Of Birth' do
        = p.input_field :dateOfBirth, :readonly => true
        %a{:href => '#', :id => 'imgCalendar', :class => 'datePicker'}
          = image_tag('Calendar_scheduleHS.png', :alt => 'Pick date from calendar' )
        = link_to 'Need Help?', calenderhelp_path, "data-toggle" => "modal", "data-target" => "#calendermodel", :class => "lnkApprove", :remote => true, :class => 'btn btn-mini'
      = p.input :pan_number
      = p.input :passport_number
      = p.input :github_handle
      =p.input :twitter_handle
      =p.input :linkedin_name, :label => 'Linkedin Name'
    .form-actions
      - if current_user.profile.nil?
        = u.submit "Create Profile", class: 'btn btn-success'
      - else
        = u.submit "Update Profile", class: 'btn btn-success'
      - if current_user.profile.nil?
        = link_to 'Skip', leaves_path, class: 'btn btn-danger'
      - else
        = link_to 'Cancel', users_path, class: 'btn btn-danger'

      %div{:id => 'calendermodel', :class => 'modal hide fade-calenderhelp', :tabindex => '-1', :role => 'dialog', 'aria-labelledby' => 'myModalLabel', 'aria-hidden' => 'true'}
        %div{:class => 'modal-header-calenderhelp'}
          %h3 Instructions:      

        %div{:class => 'modal-body'}
          %div{:class => 'modal-footer-calenderhelp'}


app/views/users/addleaves.html.haml
- content_for :javascript do
  = javascript_include_tag 'assignLeaves', 'user'
.form
  %h3 Assign leaves
  %hr
  %label User:
  = select_tag 'user', options_from_collection_for_select(current_organization.users.ne(:email => current_user.email).entries, :id, :email), :id => "cmbuser", :prompt => "Select user"
  #assign_leaves

app/views/users/assignleaves.js.haml
$('#assign_leaves').html('#{escape_javascript(render :partial => 'frmassignleaves')}')

app/views/users/calenderhelp.js.haml
$('.modal-body').html('#{escape_javascript(render :partial => 'calenderhelp')}')

app/views/users/chengemanager.html.haml
%h1 Change Manager
= render 'chengemanager'
%br
= link_to 'Cancel', users_path

app/views/users/index.html.haml
- content_for :javascript do
  = javascript_include_tag 'user'
.form
  %h3 Registered users
  %hr

  %table.table
    %thead
      %tr
        %th Employee Name
        %th Employee ID
        %th Role
        %th Probation end date
        - if current_user.roles == 'Admin'
          %th Action
    %tbody
      - @users.each do |user|
        %tr     
          %td= user.employee_name
          - if user.profile.nil?
            %td= user.employee_id
          - else
            %td= link_to user.employee_id, profile_path(user)
          %td= user.roles
          %td= user.probation_end_date.to_s
          - if can? :update, user, :id => user.id
            %td
              = link_to 'Edit', edit_user_path(user), :class => 'btn btn-mini'
              = link_to 'Remove', hide_path(user), data: { confirm: 'Are you sure?' }, :class => 'btn btn-mini'
              = link_to 'Change Role', chengeroles_path(user), :class => 'btn btn-mini'
              - if user.roles == 'Employee' 
                = link_to 'Change Manager', chengemanager_path(user), :class => 'btn btn-mini'
              - if user.invitation_token != nil
                = link_to 'Resend Invitation', reinvite_path(user), :remote => true, :class => 'btn btn-mini'

  %br
  %br
  - if current_user.profile.nil?
    = link_to 'Create profile', edit_user_path(current_user), class: 'btn btn-success'
  - else
    = link_to 'My profile', profile_path(current_user), class: 'btn btn-success'
    = link_to 'Edit profile', edit_user_path(current_user), class: 'btn btn-success'
%br

app/views/users/leave_summary_on_roles.js.haml
$('#tblLeaveSummary').html('#{escape_javascript(render :partial => 'leave_summary_on_roles')}')

app/views/users/leavessummary.html.haml
.form
  %h3 Leaves summary
  %hr
  %table.table
    %thead
      %tr
        %th Assigned date
        - @leave_types.each do |lt|
          %th= lt.name + " [Assign/Available]"
    %tbody   
      %tr
        - @leave_details.each do |l|
          - date = l.assign_date
          %td= date.present? ? date : ''
          - @leave_types.each do |lt|              
            %td="#{l.assign_leaves[lt.id.to_s]} / #{l.available_leaves[lt.id.to_s]}"
    

app/views/users/new.html.haml
= simple_form_for @user, html: {:method => :post} do |f|
  = f.error_notification
  .form-inputs

  = f.input :email

  %h2 Please select role:
  = f.input :roles, :collection => ["Admin", "HR", "Manager", "Employee"], :prompt => "Select role"

  = f.button :submit, :class => 'btn-success'

app/views/users/profile.html.haml
.form
  %h3 Profile
  %hr
  %h4 Personal information:
  %table.table 
    %tr
      %th Name
      %th Local Address
      %th Permanent Address
      %th Date Of Birth
      %th Contact Number
    %tr
      %td= @user.profile.name
      %td= @user.profile.local_address
      %td= @user.profile.permanent_address
      %td= @user.profile.dateOfBirth.strftime("%A, %B %d, %Y")
      %td= @user.profile.phone_number
  %h4 General information:
  %table.table
    %tr
      %th Pan Number
      %th Passport Number
      %th Employee Id
      %th Joining Date
      %th Role
    %tr
      %td= @user.profile.pan_number
      %td= @user.profile.passport_number
      %td= @user.employee_id
      %td= @user.join_date.strftime("%A, %B %d, %Y")
      %td= @user.roles

  %h4 social media information:
  %table.table
    %tr
      %th Github Handle
      %th Twitter Handle
      %th Linkedin Name
    %tr
      %td= @user.profile.github_handle
      %td= @user.profile.twitter_handle
      %td= @user.profile.linkedin_name

%br
= link_to 'Back', users_path, class: 'btn btn-success'

app/views/users/reinvite.js.haml
$('.container-fluid').before("<div id='flash-notice' class='flash alert alert-notice global' style='display: none;'> <a data-dismiss='alert' class='close'> </a>The Invitation has been send to user. </div>")


app/views/users/upload_csv.html.haml
- content_for :javascript do
  = javascript_include_tag 'user'
.upload
  .form
    %h3 Upload file
    %hr
    - if browser.ie? && browser.version.to_i <=8
      %b This page is not supporting your browser.
    - else
      %i Note:
      %br
      You should download the sample file before uploading your file and make your file acording to that.
      %br
      Once you made it, save that file in CSV format.
      %br
      Download that file from:
      = link_to "Here", '/sam.xlsm'
    %hr
    = simple_form_for @organization, url: upload_csv_path(@organization.id), :method => :put,  html: {:class => 'form-horizontal', :multipart => true} do |f|
      = f.error_notification
      = f.file_field :csv_attachment

      .form-actions
        = f.submit "Upload file", :class => "btn btn-success"
        = link_to "Cancel", users_path, :class => "btn btn-danger"
