config/routes.rb
JoshIntranet::Application.routes.draw do


devise_for :users, :path_names => {
    :sign_in => 'login',
    :sign_out => 'logout',
    :controller => {:invitations => 'devise/invitations'},
    :root_path => 'leaves#index'    
  }
  
  match '/signup' => 'organizations#new', via: :get, as: :signup 
  match '/signup' => 'organizations#create', via: :post, as: :signup


  constraints(OrganizationRoutes) do
    match "/" => 'dashboard#index'
    resources :users
    resources :leaves do
      get :approve, on: :member
      put :approve, on: :member
      get :rejectStatus, on: :member
      put :rejectStatus, on: :member
    end

    resources :leave_details
    resources :leave_types

    match '/addleaves' => 'users#addleaves', :via => :get
    match '/users/:user_id/assignleaves' => 'users#assignleaves', :via => [:get, :post], as: :assignleaves
    match '/users/:user_id/profile' => 'users#profile', :via => [:get, :post], as: :profile
    match '/users/:user_id/reinvite' => 'users#reinvite', :via => :get, as: :reinvite
    match '/leavessummary' => 'users#leavessummary', :via => :get,  as: :leavessummary
    match '/users/:user_id/chengeroles' => 'users#chengeroles', :via => [:get, :post], as: :chengeroles
    match '/users/:user_id/chengemanager' => 'users#chengemanager', :via => [:get, :post], as: :chengemanager
    match '/organization/:organization_id/csv' => 'users#upload_csv', :via => [:get, :put ], as: :upload_csv
    match '/managers' => 'users#managers', :via => :get, as: :managers
    match '/leave_summary_for_roles' => 'users#leave_summary_for_roles', :via => :get 
    match '/users/:user_id/leave_summary_on_roles' => 'users#leave_summary_on_roles', :via => [:get, :post], as: :leave_summary_on_roles
    match 'calenderhelp' => 'home#calenderhelp', :via => :get
  end









  root :to => 'home#index'


end

app/models/leave.rb

class Leave
  include Mongoid::Document
  belongs_to :user
  belongs_to :leave_type
  belongs_to :organization

  paginates_per 10

  field :reason, type: String
  field :starts_at, type: Date
  field :ends_at, type: Date
  field :contact_address, type: String
  field :contact_number, type: Integer
  field :status, type: String
  field :reject_reason, type: String
  field :number_of_days, type: Float

  validates :reason, :contact_address, :contact_number, :leave_type_id, :number_of_days,  :presence => true
  validates :starts_at, :presence => true
  validates :ends_at, :presence => true
  validates :reject_reason, :presence => true, :if => :reject_reason_validation?
  validates :contact_number, :numericality => {:only_integer => true}
  validates :number_of_days, :numericality => true
  validate :validates_all

  def reject_reason_validation?
    status == "Rejected"
  end

  def access_params(params, available_leaves)
    @leave_params = params
    @available_leaves = available_leaves
  end

  def valid_date(date)
regexp = /\d{2}\/\d{2}\/\d{4}/
date = date.to_s
    if date.include?("/")
      arr_date = date.split("/")
    elsif date.include?("-")
            arr_date = date.split("-")
    end
    if regexp.match(date) != nil
      if arr_date != nil && arr_date.length == 3
        if Date.valid_date?(arr_date[2].to_i, arr_date[1].to_i, arr_date[0].to_i)
          return true
        end
      end
    end
    return false
  end

  def validates_all
    if @available_leaves == nil
      errors[:base] << "Leaves are not assigned for you. Please contact your administrator"
    else
      leave_type = nil
      if @leave_params != nil
        if @leave_params["leave_type_id"] != nil && @leave_params["leave_type_id"] != ""
          leave_type = LeaveType.find(@leave_params["leave_type_id"])
          if number_of_days != nil
            if leave_type.can_apply != nil
              if number_of_days > leave_type.can_apply
                errors.add(:number_of_days, "Number of leaves are more. You can apply for #{leave_type.can_apply}")
              end
            end
            number_days = @available_leaves[@leave_params[:leave_type_id]]
            if number_of_days > number_days.to_f
              errors.add(:number_of_days, "Leaves are more than available. Available leaves are #{@available_leaves[@leave_params["leave_type_id"]]}")
            end
          end
        end
      end
      if starts_at != nil
        if valid_date(starts_at) != true
          errors.add(:starts_at, "Invalid start date")
        elsif ends_at != nil && starts_at > ends_at
          errors.add(:starts_at, "Start date cannot be greater than end date")
        end
      end
      if ends_at != nil
        if !valid_date(ends_at)
          errors.add(:ends_at, "Invalid end date")
        elsif starts_at != nil && ends_at < starts_at
          errors.add(:ends_at, "End date should not be before start date")
        end
      end
    end
  end

  def self.increment_leaves
    Organization.all.each do |organization|
      leave_types = organization.leave_types.where(:auto_increament => true)
      users = organization.users.ne(:roles => "Admin")
      leave_types.each do |lt|
        users.each do |u|
          u.leave_details.each do |l|
            if l.assign_date.year == Date.today.year
              l.assign_leaves[lt.id.to_s] = l.assign_leaves[lt.id.to_s].to_f + lt.number_of_leaves
              l.available_leaves[lt.id.to_s] = l.available_leaves[lt.id.to_s].to_f + lt.number_of_leaves
              l.save
            end
          end
        end
      end
    end
  end

  def self.assign_leave
    Organization.all.each do |org|
      leave_types = org.leave_types.all
      admin = org.users.where(roles: "Admin")
      users = org.users.ne(roles: "Admin")
      assign_leaves = {}
      leave_types.each do |leave_type|
        if leave_type.auto_increament == true
          num_leaves = leave_type.number_of_leaves
        else
          num_leaves = leave_type.max_no_of_leaves
        end
        assign_leaves[leave_type.id] = num_leaves                   
      end
      users.each do |user|
        user.leave_details.build
        user.leave_details.assign_date = Date.today
        user.leave_details.assign_leaves = assign_leaves
        user.leave_details.available_leaves = assign_leaves 
        user.leave_details.save
        UserMailer.assignLeaveReport(user).deliver
      end
      UserMailer.assignLeaveReport(admin).deliver
    end
  end
end

app/models/leave_type.rb
class LeaveType
  include Mongoid::Document
  belongs_to :organization
  has_many :leaves, dependent: :destroy

  field :name, type: String
  field :max_no_of_leaves, type: Float
  field :auto_increament, type: Boolean
  field :number_of_leaves, type: Float 
  field :can_apply, type: Float
  field :carry_forward, type: Boolean 
  validates :name, :max_no_of_leaves, presence: true
  validates :number_of_leaves, :presence => true, :if => :require_validation? 
  validates  :max_no_of_leaves, :numericality => { :greater_than => 0}
  validates :number_of_leaves, :can_apply, :numericality => { :greater_than => 0}, :allow_blank => true 
  validates :number_of_leaves, :can_apply,  :numericality => { :less_than_or_equal_to => :max_no_of_leaves}, :allow_blank => true 


  def require_validation?
    auto_increament == true
  end


  def as_json(option = {})
    option = { :only => [:id, :type, :max_no_of_leaves, :auto_increament, :number_of_leaves, :carry_forward]} if option.nil?
      super
  end
end

app/controllers/leaves_controller.rb
class LeavesController < ApplicationController
  before_filter :current_organization
  load_and_authorize_resource

  def index        
    @leaves = current_organization.leaves.accessible_by(current_ability).desc(:id)
    current_user.leave_details.each do |l|
      if l.assign_date.year == Date.today.year
        @leave_details = l
    end
    end
    @leave_types = current_organization.leave_types
    respond_to do |format|
      format.html # index.html.haml
      format.json { render json: @leaves }
    end
    p @leaves
  end

  def show
    @leave = Leave.find(params[:id])

    respond_to do |format|
      format.html # show.html.haml
      format.json { render json: @leave }
    end
  end

  def new
    @leave = Leave.new
    @profile = current_user.profile
  end

  def create
    @leave = Leave.new(params[:leave])
    @leave.user = current_user
    @leave.organization = current_organization
    available_leaves = available_leaves(@leave.user)
    @leave.access_params(params[:leave], available_leaves)
    @leave.status = "Pending"
    respond_to do |format|
      if @leave.save
        if current_user.roles == 'HR'
          user_role = current_organization.users.where(:roles => 'Admin').collect(&:email)
          UserMailer.leaveReport(@leave, current_user, user_role).deliver
        elsif current_user.roles == 'Manager'
          user_role = current_organization.users.in(:roles => ['HR', 'Admin']).collect(&:email)
          UserMailer.leaveReport(@leave, current_user, user_role).deliver
        elsif current_user.roles == 'Employee' && current_user.manager.nil?
          user_role = current_organization.users.in(:roles => ['HR', 'Admin']).collect(&:email)
          UserMailer.leaveReport(@leave, current_user, user_role).deliver
        else
          user_role = current_organization.users.in(:roles => ['Admin', 'HR']).collect(&:email).push(current_user.manager.email)
          UserMailer.leaveReport(@leave,current_user, user_role).deliver
          format.json {render json: @leave, status: :created}
        end
	format.html {redirect_to leaves_path, notice: 'Your Leave Application is pending for Approval.' }
        format.json {render json: @leave, status: :created}
      else
        @profile = current_user.profile
        format.html {render action: "new"}
	format.json { render json: @leave.errors, status: :unprocessable_entity }
      end
    end
  end

  def edit
    @leave = Leave.find(params[:id])    
  end

  def update
    @leave = Leave.find(params[:id])
    @leave.access_params(params[:leave], available_leaves(@leave.user))
    respond_to do |format|
      if @leave.update_attributes(params[:leave])
        format.html { redirect_to leaves_path, notice: 'Leave is successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @leave.errors, status: :unprocessable_entity }
      end
    end    
  end

  def approve
    @leave = Leave.find(params[:id])
    if request.put?
      @leave.access_params(params[:leave], @leave.user.leave_details.last.available_leaves)
      respond_to do |format|
        @leave.status = "Approved"
        if @leave.update_attributes(params[:leave])
          leave_details = @leave.user.leave_details.last
          diduct_leaves = leave_details.available_leaves[@leave.leave_type.id.to_s].to_f - params[:leave]["number_of_days"].to_f
          leave_details.available_leaves[@leave.leave_type.id.to_s] = diduct_leaves.to_f
          leave_details.save
          UserMailer.approveLeave(@leave, current_user).deliver
          format.html { redirect_to leaves_path, notice: 'Leave is successfully approved.' }          
          format.js
        else
          format.html { render   "approve.js" }
          format.json { render json: @leave.errors, status: :unprocessable_entity }
          format.js
        end
      end
    end
  end

  def rejectStatus
    @leave = Leave.find(params[:id])
    if request.put?
      available_leaves = available_leaves(@leave.user)
      @leave.access_params(params[:leave], available_leaves)
      @leave.status = "Rejected"
      p @leave.reject_reason = params[:leave][:reject_reason]
      p params[:leave][:reject_reason]
      respond_to do |format|
        if @leave.update_attributes(params[:leave])
          UserMailer.rejectStatusLeave(@leave, current_user).deliver
          format.html { redirect_to leaves_path, notice: 'Leave is successfully rejected.' }     
            format.js
        else
          format.html { render  "rejectStatus.js"}
	  format.xml { render json: @leave.errors, status: :unprocessable_entity }
	  format.js
        end
      end
    end
  end

  def destroy 
    @leave = Leave.find(params[:id])
    user = User.find(current_user)
    if current_user.roles == "Admin" && @leave.status == "Approved"
      @leave.user.leave_details.each do |l|
        if l.assign_date.year == Date.today.year
          tmp_num = l.available_leaves[@leave.leave_type_id.to_s].to_f
          tmp_num = tmp_num + @leave.number_of_days
          l.available_leaves[@leave.leave_type_id.to_s] = tmp_num
          l.save
          @leave.destroy
          UserMailer.cansleLeave(@leave, user).deliver
          redirect_to leaves_url, notice: 'Applied leave is deleted successfully.'
        end
      end
    elsif current_user.roles == 'Admin'
      @leave.destroy
      UserMailer.cansleLeave(@leave, user).deliver
      redirect_to leaves_url, notice: 'Applied leave is deleted successfully.'
    else
      if @leave.status == 'Pending'
        @leave.destroy
        user_r = current_organization.users.where(:roles => 'Admin').collect(&:email)
        UserMailer.destroyLeave(user, user_r).deliver
	        redirect_to leaves_url, notice: 'Your applied leave is deleted successfully.'
      else
        redirect_to leaves_path, notice: 'You cannot cancel the leave.'
      end
    end  
  end

  private
  def available_leaves(user)
    available_leaves = nil
    if user.leave_details != nil
      user.leave_details.each do |l|
        if l.assign_date.year == Date.today.year
          available_leaves = l.available_leaves
        end
      end
    end
    return available_leaves
  end
end

app/helpers/leaves_helper.rb
module LeavesHelper
end

app/views/leaves/_approve.html.haml
- content_for :javascript do
  = javascript_include_tag 'leaves', 'setup_apply_leave'
= simple_form_for @leave, :url => approve_leave_path(@leave), :method => :put, html: {:class => 'form-horizontal'}, :remote =>true do |f| 
  = f.error_notification
  = f.input :leave_type_id, :as => :hidden, :input_html => {:value => "#{@leave.leave_type_id}" }
  = f.input :starts_at, :label => 'Start date', :input_html => {:value => "#{@leave.starts_at.strftime("%A, %B %d, %Y")}", :class => "datepicker"}, :readonly => true
  = f.input :ends_at, :label => 'End date', :input_html => {:value => "#{@leave.ends_at.strftime("%A, %B %d, %Y")}", :class => "datepicker"}, :readonly => true
  = f.input :number_of_days, :input_html => {:value => "#{@leave.number_of_days}"}
  = f.submit "Submit", class: "btn btn-success", :id => "approvebutton"
  = link_to " Cancel", leaves_path, class: "btn btn-danger", :id => 'cancel_approved_leave'
:javascript
  $('datepicker').datepicker( {
     dateFormat: "dd/mm/yy",  
     changeMonth: true,
     changeYear: true
   })

app/views/leaves/_form.html.haml
- content_for :javascript do
  = javascript_include_tag 'leaves', 'setup_apply_leave'
= simple_form_for @leave, html: {:class => 'form-horizontal'} do |f|
  = f.error_notification
  = f.association :leave_type, :collection => current_organization.leave_types.all.entries, :prompt => "Select leave type"
  = f.input :reason
  = f.input :starts_at, :label => 'Select start date' do
    = f.input_field :starts_at, :readonly => true
    %a{:href => '#', :id => 'imgCalendar_start_date', :class => 'datePicker'}
      = image_tag('Calendar_scheduleHS.png', :alt => 'Pick date from calendar' )
  = f.input :ends_at, :label => 'Select end date' do
    = f.input_field :ends_at, :readonly => true 
    %a{:href => '#', :id => 'imgCalendar_end_date', :class => 'datePicker'}
      = image_tag('Calendar_scheduleHS.png', :alt => 'Pick date from calendar' )
  = f.input :number_of_days
  - if current_user.profile.nil?
    = f.input :contact_address, :required => true
  - else
    = f.input :contact_address, :as => :text, :input_html => {:value => "#{current_user.profile.local_address}", :cols => 20, :rows => 5}
  - if current_user.profile.nil?
    = f.input :contact_number, :required => true
  - else
    = f.input :contact_number, :input_html => {:value => "#{current_user.profile.phone_number}"}
  .form-actions
    = f.submit "Apply", class: 'btn btn-success'
    = link_to 'Cancel', leaves_path, class: 'btn btn-danger'

:javascript
  $('#datepicker').datepicker({})

app/views/leaves/_rejectStatus.html.haml
- content_for :javascript do
  = javascript_include_tag 'leaves'
= simple_form_for @leave, :url => rejectStatus_leave_path(@leave), html: {:class => 'form-horizontal'}, :remote =>true do |f|
  = f.error_notification
  = f.input :reject_reason, :as => :text, :required => true, :input_html => {:cols => 20, :rows => 5}
  = f.submit "Submit", class: "btn btn-success", :id => "rejectButton"
  = link_to "Cancel", leaves_path, class: "btn btn-danger", :id => 'cancelationOfReject'


app/views/leaves/approve.js.haml
$('.modal-body-approve').html('#{escape_javascript(render :partial => 'approve')}')
$('#error').html('')
- if @leave.errors.any?
  $('.modal-body-approve').html('#{escape_javascript(render :partial => 'approve')}')
- else
  - if @leave.update_attributes
    window.location.href = "leaves"
submitButton = $('#approvemodel #approvebutton')
cancelApprovedLeave = $('#approvemodel #cancel_approved_leave')
submitButton.click(function() {
cancelApprovedLeave.removeAttr('href');
submitButton.attr('disabled', true);
});

app/views/leaves/edit.html.haml
%h1 Editing leave

= render 'form'



app/views/leaves/index.html.haml
- content_for :javascript do
  = javascript_include_tag 'leaves'
.form
  - if current_user.roles != "Admin"
    %h4 Leaves summary for an year #{Date.today.year}
    %hr

    - if @leave_details != nil
      - @leave_types.each do |lt|
        %br   
        %br  
        %label.span4 #{lt.name} [Assign/Available]:
        - if @leave_details.assign_leaves[lt.id.to_s] != ""
          .span4 #{@leave_details.assign_leaves[lt.id.to_s]} / #{@leave_details.available_leaves[lt.id.to_s]}

  %br
  %hr	
  %h4 Applied leaves
  %hr

  %table.table
    %thead 
      %tr
        %th User
        %th Leave type
        %th Reason:
        %th Start date:
        %th End date:
        %th Status:
        %th Action
    %tbody
      - @leaves.each do |leave|                                       
        %tr          
          %td= leave.user.profile.nil? ? leave.user.email : leave.user.name                    
          %td= leave.leave_type.name
          %td= leave.reason
          %td= leave.starts_at.strftime("%A, %B %d, %Y")
          %td= leave.ends_at.strftime("%A, %B %d, %Y")
          %td{:class => "status"}= leave.status
          %td
            = link_to 'Show', leave, :class => 'btn btn-mini'
            - if leave.status == "Pending"
              - if can? :approve, leave
                = link_to 'Approve', approve_leave_path(leave), "data-toggle" => "modal", "data-target" => "#approvemodel", :class => "lnkApprove", :remote => true, :class => 'btn btn-mini'
              - if can? :rejectStatus, leave
                = link_to 'Reject', rejectStatus_leave_path(leave),  "data-toggle" => "modal", "data-target" => "#rejectmodal", :html => {:class => 'lnkReject'}, :remote => true, :class => 'btn btn-mini'
              - if can? :edit, leave
                = link_to 'Edit', edit_leave_path(leave), :class => 'btn btn-mini'
              - if can? :destroy, leave
                = link_to 'Delete', leave, method: :delete, data: { confirm: 'Are you sure?' }, :class => 'btn btn-mini'
            - else
              - if current_user.roles == "Admin"
                - if can? :destroy, leave
                  = link_to 'Delete', leave, method: :delete, data: { confirm: 'Are you sure?' }, :class => 'btn btn-mini'

      %div{:id => "rejectmodal", :class => "modal hide fade rejectmodal", :tabindex => "-1", :role => "dialog", "aria-labelledby" => "myModalLabel", "aria-hidden" => "true"}
        %div{:class => "modal-header"}
          %h3 Reject leaves
        %div{:class => "modal-body"}
        %div{:class => "modal-footer"} 
      %div{:id => 'approvemodel', :class => 'modal hide fade-approve', :tabindex => '-1', :role => 'dialog', 'aria-labelledby' => 'myModalLabel', 'aria-hidden' => 'true'}
        %div{:class => 'modal-header-approve'}
          %h3 Approve leave      

        %div{:class => 'modal-body-approve'}
          %div{:class => 'modal-footer-approve'}
    
  %br



app/views/leaves/new.html.haml
.header
 %h1 Apply Leaves
 .content
  = render 'form'

app/views/leaves/rejectStatus.js.haml
$('.modal-body').html('#{escape_javascript(render :partial => 'rejectStatus')}')
$('#error').html('')
- if @leave.errors.any?
  console.log('Error');
  $('.modal-body').html('#{escape_javascript(render :partial => 'rejectStatus')}')
- else
  - if @leave.update_attributes
    window.location.href = "leaves"

submit = $('#rejectmodal #rejectButton')
cancel = $('#rejectmodal #cancelationOfReject')
submit.click(function() {
cancel.removeAttr('href');
submit.attr('disabled', true);
});

app/views/leaves/show.html.haml
- content_for :javascript do
  = javascript_include_tag 'leaves'
%table.table
  %tr
    %th User
    %th Leave type:
    %th Reason:
    %th Start date:
    %th End date:
    %th Contact address:
    %th Contact number:
    %th Status:
    - if @leave.status == "Rejected"
      %th Rejection reason:
    %th
    %th
    %th
  %tr
    - if @leave.user.profile.nil?
      %td= @leave.user.email
    - else
      %td= @leave.user.name
    %td= @leave.leave_type.name
    %td= @leave.reason
    %td= @leave.starts_at
    %td= @leave.ends_at
    %td= @leave.contact_address
    %td= @leave.contact_number
    %td{:class => "status"}= @leave.status
    - if @leave.status == "Rejected"
      %td= @leave.reject_reason

%br
%br

= link_to 'Back', leaves_path, class: 'btn btn-large btn-success'