config/routes.rb
JoshIntranet::Application.routes.draw do


devise_for :users, :path_names => {
    :sign_in => 'login',
    :sign_out => 'logout',
    :controller => {:invitations => 'devise/invitations'},
    :root_path => 'leaves#index'    
  }
  
  match '/signup' => 'organizations#new', via: :get, as: :signup 
  match '/signup' => 'organizations#create', via: :post, as: :signup


  constraints(OrganizationRoutes) do
    match "/" => 'dashboard#index'
    resources :users
    resources :leaves do
      get :approve, on: :member
      put :approve, on: :member
      get :rejectStatus, on: :member
      put :rejectStatus, on: :member
    end

    resources :leave_details
    resources :leave_types

    match '/addleaves' => 'users#addleaves', :via => :get
    match '/users/:user_id/assignleaves' => 'users#assignleaves', :via => [:get, :post], as: :assignleaves
    match '/users/:user_id/profile' => 'users#profile', :via => [:get, :post], as: :profile
    match '/users/:user_id/reinvite' => 'users#reinvite', :via => :get, as: :reinvite
    match '/leavessummary' => 'users#leavessummary', :via => :get,  as: :leavessummary
    match '/users/:user_id/chengeroles' => 'users#chengeroles', :via => [:get, :post], as: :chengeroles
    match '/users/:user_id/chengemanager' => 'users#chengemanager', :via => [:get, :post], as: :chengemanager
    match '/organization/:organization_id/csv' => 'users#upload_csv', :via => [:get, :put ], as: :upload_csv
    match '/managers' => 'users#managers', :via => :get, as: :managers
    match '/leave_summary_for_roles' => 'users#leave_summary_for_roles', :via => :get 
    match '/users/:user_id/leave_summary_on_roles' => 'users#leave_summary_on_roles', :via => [:get, :post], as: :leave_summary_on_roles
    match 'calenderhelp' => 'home#calenderhelp', :via => :get
  end









  root :to => 'home#index'


end

app/models/organization.rb
class Organization
  include Mongoid::Document
  include Mongoid::Slug
  include Mongoid::Paperclip 
  has_mongoid_attached_file :csv_attachment
  attr_accessible :csv_attachment, :name, :address1, :address2, :city, :country, :zip, :contact_number, :users_attributes

  field :name
  slug :name
  field :address1
  field :address2
  field :city
  field :country
  field :zip, type: Integer
  field :contact_number, type: Integer

  has_many :users, dependent: :destroy
  has_many :leave_types, dependent: :destroy
  has_many :leaves, class_name: "Leave", dependent: :destroy
  accepts_nested_attributes_for :leave_types
  validates :name, :address1, :city, :country, :zip, :contact_number, presence: true
  validates :contact_number, :zip, :numericality => {:only_integer => true}
  validates :name, uniqueness: true
  validates_attachment :csv_attachment, content_type:  {:content_type => ['text/csv', 'application/vnd.ms-excel']}
  accepts_nested_attributes_for :users, allow_destroy: true
end

app/controllers/organizations_controller.rb
require 'chagol'
class OrganizationsController < ApplicationController
  skip_before_filter :current_organization, :authenticate_user!, only: [:new, :create]


  # GET /organizations
  # GET /organizations.json
  def index
    @organizations = Organization.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @organizations }
    end
  end

  # GET /organizations/1
  # GET /organizations/1.json
  def show
    @organization = Organization.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @organization }
    end
  end

  # GET /organizations/new
  # GET /organizations/new.json
  def new
    @organization = Organization.new
    @organization.users.build
    render layout: 'home'
  end

  # GET /organizations/1/edit
  def edit
    @organization = Organization.find(params[:id])
  end

  # POST /organizations
  # POST /organizations.json
  def create
    @organization = Organization.new(params[:organization])

    respond_to do |format|
      if @organization.save
        UserMailer.organizationRegistration(@organization).deliver
        format.html { redirect_to root_url, notice: 'Your account successfully created.' }
        format.json { render json: @organization, status: :created, location: @organization }
      else
        format.html { render action: "new", layout: 'home' }
        format.json { render json: @organization.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /organizations/1
  # PUT /organizations/1.json
  def update
    @organization = Organization.find(params[:id])

    respond_to do |format|
      if @organization.update_attributes(params[:organization]).put
        format.html { redirect_to @organization, notice: 'Organization was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @organization.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /organizations/1
  # DELETE /organizations/1.json
  def destroy
    @organization = Organization.find(params[:id])
    @organization.destroy

    respond_to do |format|
      format.html { redirect_to organizations_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/organizations_helper.rb
module OrganizationsHelper
end

app/views/organizations/_form.html.haml
- content_for :javascript do
  = javascript_include_tag 'user', 'organizations' 
= simple_nested_form_for @organization, url: signup_path, html: {:class => 'form-horizontal'} do |f|
  = f.error_notification

  .form-inputs
    = f.input :name, :label => "Organization name"
    = f.input :address1
    = f.input :address2
    = f.input :city
    = f.input :country
    = f.input :zip
    = f.input :contact_number
    = f.simple_fields_for :users do |u|
      = u.input :email
      = u.input :password
      = u.input :password_confirmation
      = u.hidden_field :roles, :value => 'Admin'
      = u.hidden_field :join_date, :value => Date.today
      = u.hidden_field :employee_id, :value => '001'


  .form-actions
    = f.button :submit, class: 'btn-success'

app/views/organizations/edit.html.haml
%h1 Editing organization

= render 'form'

= link_to 'Show', @organization
\|
= link_to 'Back', organizations_path

app/views/organizations/index.html.haml
%h1 Listing organizations

%table
  %tr
    %th
    %th
    %th

  - @organizations.each do |organization|
    %tr
      %td= link_to 'Show', organization
      %td= link_to 'Edit', edit_organization_path(organization)
      %td= link_to 'Destroy', organization, method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'New Organization', new_organization_path

app/views/organizations/new.html.haml
.registration
  .header
    %h2 Sign up 

  .content
    = render 'form'


app/views/organizations/show.html.haml
%p#notice= notice


= link_to 'Edit', edit_organization_path(@organization)
\|
= link_to 'Back', organizations_path