config/routes.rb
JoshIntranet::Application.routes.draw do


devise_for :users, :path_names => {
    :sign_in => 'login',
    :sign_out => 'logout',
    :controller => {:invitations => 'devise/invitations'},
    :root_path => 'leaves#index'    
  }
  
  match '/signup' => 'organizations#new', via: :get, as: :signup 
  match '/signup' => 'organizations#create', via: :post, as: :signup


  constraints(OrganizationRoutes) do
    match "/" => 'dashboard#index'
    resources :users
    resources :leaves do
      get :approve, on: :member
      put :approve, on: :member
      get :rejectStatus, on: :member
      put :rejectStatus, on: :member
    end

    resources :leave_details
    resources :leave_types

    match '/addleaves' => 'users#addleaves', :via => :get
    match '/users/:user_id/assignleaves' => 'users#assignleaves', :via => [:get, :post], as: :assignleaves
    match '/users/:user_id/profile' => 'users#profile', :via => [:get, :post], as: :profile
    match '/users/:user_id/reinvite' => 'users#reinvite', :via => :get, as: :reinvite
    match '/leavessummary' => 'users#leavessummary', :via => :get,  as: :leavessummary
    match '/users/:user_id/chengeroles' => 'users#chengeroles', :via => [:get, :post], as: :chengeroles
    match '/users/:user_id/chengemanager' => 'users#chengemanager', :via => [:get, :post], as: :chengemanager
    match '/organization/:organization_id/csv' => 'users#upload_csv', :via => [:get, :put ], as: :upload_csv
    match '/managers' => 'users#managers', :via => :get, as: :managers
    match '/leave_summary_for_roles' => 'users#leave_summary_for_roles', :via => :get 
    match '/users/:user_id/leave_summary_on_roles' => 'users#leave_summary_on_roles', :via => [:get, :post], as: :leave_summary_on_roles
    match 'calenderhelp' => 'home#calenderhelp', :via => :get
  end









  root :to => 'home#index'


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  rescue_from CanCan::AccessDenied do |exception|

redirect_to root_url, :alert => exception.message
  end

  protect_from_forgery :except => :managers
  before_filter :authenticate_user!
  skip_before_filter :authenticate_user!, :only => :managers

  def after_sign_in_path_for(resource)
    if current_organization != nil
      if resource && resource.sign_in_count == 1
        edit_user_path(resource)
      elsif resource
          leaves_path
      end
    end
  end

  def after_invite_path_for(resource)
    user = resource
    l_t = params[:leave_type]
    pay = params[:pay_role]
    if params[:user][:pay_role] == "1"
      @leave_types = current_organization.leave_types.where(:id => l_t)
    else
      @leave_types = current_organization.leave_types.all
    end
    assign_leaves =calculate_leaves
    user.leave_details.build
    user.leave_details.last.assign_date = Date.today
    user.leave_details.last.assign_leaves = assign_leaves
    user.leave_details.last.available_leaves = assign_leaves
    user.leave_details.last.save
    users_path
  end

  def calculate_leaves
    start_date = Time.zone.now.to_date
    end_date = Time.zone.now.end_of_year.to_date
    months = end_date.month - start_date.month
    assign_leaves = {}
    @leave_types.each do |lt|
      if lt.auto_increament == true
        num_leaves = lt.number_of_leaves
      else
        num_leaves = (lt.max_no_of_leaves/12.0*months).round(0)
      end
      assign_leaves[lt.id] = num_leaves
    end
    return assign_leaves
  end

  def current_organization
    if extract_subdomain != nil
      @current_organization = Organization.find_by_slug!( extract_subdomain )
      # make sure we can only access the current users account!
      if @current_organization != nil && current_user != nil && current_user.organization == @current_organization
        return @current_organization
      else
        sign_out
        return nil
      end
    else
      return nil
    end
  end
  helper_method :current_organization

	private

  def extract_subdomain
    subdomain = request.subdomains.first
    if subdomain == "www" 
      subdomain = request.subdomains.last
    end
    return subdomain
  end

  def authenticate_inviter!
    unless current_user.roles == 'Admin'
      redirect_to root_url, :alert => "You are not authorized to access this page."
    end
    super
  end


end
	

app/helpers/application_helper.rb
module ApplicationHelper

  def show_flash_messages(options = {})
    ret = []
    flash.each do |key, value|
      ret << content_tag( :div, {class: "flash alert alert-#{key} global", id: "flash-#{key}"}) do
        content = haml_tag "a.close", "data-dismiss" => "alert" 
        haml_concat value
      end
    end
    return_string = ret.join("\n")
    return return_string.respond_to?(:html_safe) ? return_string.html_safe : return_string
  end
end

app/views/application/_footer.html.haml
%p &copy; Company 2012

.row-fluid
  .span4
    %ul.nav
      %li
        %p Developed by
      %li
        %a{:href => "http://techvision.net.in"}
          %img{:src =>'/assets/techvision4.jpg', :alt => 'TechVision', :width => "125px"}
  



app/views/application/_header.html.haml
.navbar.navbar-inverse
  .navbar-inner
    .container-fluid
      %a.btn.btn-navbar{"data-target" => ".nav-collapse", "data-toggle" => "collapse"}
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      %a.brand{:href => "http://niwantvision.com"}
        %img{:src =>'/assets/NiwantLogo.jpg', :alt => 'Niwant', :width => "70px"}
        %a.brand{:href => "#"} Leave Management System 
      .nav-collapse.collapse
        - if user_signed_in?
          %p.navbar-text.pull-right
            Logged in as
            %a.navbar-link{:href => "#"}= current_user.email 
            = link_to 'Log out', destroy_user_session_path, method: :delete
          %ul.nav{:id => "myTab"}
            %li.active
              %a{:href => leaves_path} Home
            %li
              = link_to "Users", users_path
            = render 'left_menu'

            - if current_user.has_role?('Admin')
              %li
                = link_to "Leave types", leave_types_path
            - else
              %li
                = link_to "Apply leaves", new_leave_path
              %li
                = link_to 'Leaves summary', leavessummary_path

app/views/application/_left_menu.html.haml
= content_for :left_menu do
  .well.sidebar-nav
    %ul.nav.nav-list
      %li.nav-header
      - if params[:controller] == "users" && params[:action] == "edit"
        %li.active Edit Profile
      - elsif params[:controller] == "users" && params[:action] == "profile"
        %li.active Profile
      - elsif params[:controller] == "users" && params[:action] == "leavessummary"
        %li.active Leaves summary
      - elsif params[:controller] == "users" && params[:action] == "addleaves"
        %li.active Assign Leaves
      - elsif params[:controller] == "users" && params[:action] == "index"
        %li.active User
      - elsif params[:controller] == "leaves" && params[:action] == "new"
        %li.active Apply leaves
      - elsif params[:controller] == "leaves" && params[:action] == "edit"
        %li.active Edit leaves
      - elsif params[:controller] == "leaves" && params[:action] == "show"
        %li.active Show
      - elsif params[:controller] == "leaves"
        %li.active Home
      - elsif params[:controller] == "leave_types" && params[:action] == "new"
        %li.active New leave type
      - elsif params[:controller] == "leave_types" && params[:action] == "edit"
        %li.active Edit leave type
      - elsif params[:controller] == "leave_types"
        %li.active Leave Type
      - if current_organization.leave_types.empty?
      -else
        %li
          - if params[:action] != "addleaves"
            - if can? :assign_leave, @assign_leaves 
              = link_to "Assign Leaves", addleaves_path
          - if params[:controller] == "devise/invitations" && params[:action] == "new"
            %li.active Invite
          - else
            - if can? :new_user_invitation, @user
              = link_to "Invite", new_user_invitation_path
          - if params[:controller] == "users" && params[:action] == "upload_csv"
            %li.active Upload CSV and invite
          - else
            - if can? :upload_csv, @organization
              %li
                = link_to "Upload CSV and invite", upload_csv_path(current_organization.id)
          - if params[:action] == "leave_summary_for_roles"
            %li.active Leave summary on roles
          - else
            - if can? :leave_summary_on_roles, User
              %li
                = link_to 'Leave summary on roles', leave_summary_for_roles_path
	    